Created Test Main Page and Order Page
BrazhnikovJee/Java_E2E_Sprint4 pull request #1
Opened 2024-02-28 21:54 UTC by BrazhnikovJee

2024-03-01 17:02 UTC, pavel-ulan requested changes
Неплохо. Я бы даже сказал сама работа хорошая, но небольшой косяк с требованиями требует исправления.

2024-03-01 17:02 UTC, pavel-ulan commented on pom.xml
> +            <version>RELEASE</version>
**можно лучше**
в целом ок, но будь осторожнее с LTS/Release и т.п. От версии к версии могут довольно сильно меняться библиотеки. Что-то деприкейтнут, что-то станет обязательным. И в какой-то момент у тебя просто все перестанет запускаться по непонятной причине. Клево если библиотека одна, а если их пара десятков?

2024-03-01 17:02 UTC, pavel-ulan commented on src/main/java/page/MainPage.java
> +    private final By getOrderButtons = By.xpath(".//*[contains(@class,'ra12g') and text()='Заказать']");
**надо исправить**
Не забывай внимательно читать условия. Для тебя это твое ТЗ, а работа с ТЗ это первое, что должен уметь инженер.
Так в условии есть `Выпиши все элементы в список с помощью комментариев.` Вроде не самое критичное условие, но тем не менее это все еще условие задания

2024-03-01 17:02 UTC, pavel-ulan commented on src/test/java/Fierfox/TestMenuQuestions.java
> +        MainPage mainPage = new MainPage(driver);
**можно лучше**
Драйвер (впрочем как и создание объекта страницы) я бы посоветовал вынести из метода. Оставь их просто полями класса и сразу же проинициализируй. Тебе не нужен отдельный объект для каждого теста. Ни драйвер, ни страницы не изменяются, их можно спокойно переиспользовать

2024-03-01 17:02 UTC, pavel-ulan commented on src/test/java/Fierfox/TestMenuQuestions.java
> +        driver.get("https://qa-scooter.praktikum-services.ru/");
**надо исправить**
URI у тебя постоянный и должен быть вынесен, т.к. внутри теста это по сути хардкод. Сделай его константой и используй в обоих тестах

2024-03-03 01:48 UTC, BrazhnikovJee commented on pom.xml
> +            <version>RELEASE</version>
Добавил версию junit

2024-03-03 01:49 UTC, BrazhnikovJee commented on src/main/java/page/MainPage.java
> +    private final By getOrderButtons = By.xpath(".//*[contains(@class,'ra12g') and text()='Заказать']");
Добавил комменты к локаторам

2024-03-03 01:49 UTC, BrazhnikovJee commented on src/test/java/Fierfox/TestMenuQuestions.java
> +        MainPage mainPage = new MainPage(driver);
Сделал их, как поля класса

2024-03-03 01:50 UTC, BrazhnikovJee commented on src/test/java/Fierfox/TestMenuQuestions.java
> +        driver.get("https://qa-scooter.praktikum-services.ru/");
Вынес URL в отдельный класс, как константу

2024-03-06 22:30 UTC, pavel-ulan approved these changes
Да, отлично

2024-03-07 01:48 UTC, merged